In [1]:
import pandas as pd

In [2]:
fact = pd.read_csv("fact_delivery.csv")

In [3]:
print(fact.shape)

(113425, 22)

In [4]:
print(fact.columns)

Index(['order_id', 'customer_id', 'purchase_date', 'delivered_date',
       'estimated_date', 'order_status', 'product_id', 'seller_id', 'price',
       'freight_value', 'customer_city', 'customer_state', 'seller_city',
       'seller_state', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'delivery_days',
       'estimated_days', 'delay_days', 'delayed_flag'],
      dtype='str')

In [6]:
fact['purchase_date'] = pd.to_datetime(fact['purchase_date'])
fact['delivered_date'] = pd.to_datetime(fact['delivered_date'])
fact['estimated_date'] = pd.to_datetime(fact['estimated_date'])

In [7]:
fact["route_name"] = fact["seller_state"] + " -> " + fact["customer_state"]

In [9]:
fact[["seller_state", "customer_state", "route_name"]].head(10)

  seller_state customer_state route_name
0           SP             RJ   SP -> RJ
1           SP             SP   SP -> SP
2           MG             MG   MG -> MG
3           SP             SP   SP -> SP
4           PR             SP   PR -> SP
5           SP             MG   SP -> MG
6           SP             SP   SP -> SP
7           SP             SP   SP -> SP
8           SP             SP   SP -> SP
9           SP             SP   SP -> SP

In [13]:
def delivery_bucket(x):
    if pd.isna(x):
        return "Not Delivered"
    elif x < 0:
        return "Early"
    elif x == 0:
        return "On Time"
    elif x <= 3:
        return "Slight Delay"
    else:
        return "High Delay"

fact["delivery_status_bucket"] = fact["delay_days"].apply(delivery_bucket)

In [17]:
fact["delivery_status_bucket"].head(10)

0      Early
1      Early
2      Early
3      Early
4      Early
5      Early
6      Early
7      Early
8    On Time
9      Early
Name: delivery_status_bucket, dtype: str

In [18]:
fact["volume_cm3"] = (
    fact["product_length_cm"] *
    fact["product_height_cm"] *
    fact["product_width_cm"]
)

In [19]:
fact["volume_cm3"].head()

0     3528.0
1    60000.0
2    14157.0
3     2400.0
4    42000.0
Name: volume_cm3, dtype: float64

In [20]:
def weight_bucket(x):
    if pd.isna(x):
        return "Unknown"
    elif x <= 500:
        return "Light"
    elif x <= 2000:
        return "Medium"
    else:
        return "Heavy"

fact["weight_bucket"] = fact["product_weight_g"].apply(weight_bucket)

In [21]:
fact["weight_bucket"].head(10)

0    Medium
1     Heavy
2     Heavy
3     Light
4     Heavy
5     Light
6     Light
7     Heavy
8    Medium
9    Medium
Name: weight_bucket, dtype: str

In [22]:
def size_bucket(x):
    if pd.isna(x):
        return "Unknown"
    elif x <= 1000:
        return "Small"
    elif x <= 5000:
        return "Medium"
    else:
        return "Large"

fact["size_bucket"] = fact["volume_cm3"].apply(size_bucket)

In [23]:
fact["size_bucket"].head(10)

0    Medium
1     Large
2     Large
3    Medium
4     Large
5    Medium
6    Medium
7     Large
8     Large
9    Medium
Name: size_bucket, dtype: str

In [24]:
fact.head()

,order_id,customer_id,purchase_date,delivered_date,estimated_date,order_status,product_id,seller_id,price,freight_value,...,product_width_cm,delivery_days,estimated_days,delay_days,delayed_flag,route_name,delivery_status_bucket,volume_cm3,weight_bucket,size_bucket
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,2017-09-13,2017-09-20,2017-09-29,delivered,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.900002,13.290000,...,14.0,7.0,16,-9.0,0,SP -> RJ,Early,3528.0,Medium,Medium
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,2017-04-26,2017-05-12,2017-05-15,delivered,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.899994,19.930000,...,40.0,16.0,19,-3.0,0,SP -> SP,Early,60000.0,Heavy,Large
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,2018-01-14,2018-01-22,2018-02-05,delivered,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.000000,17.870001,...,33.0,8.0,22,-14.0,0,MG -> MG,Early,14157.0,Heavy,Large
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,2018-08-08,2018-08-14,2018-08-20,delivered,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.990000,12.790000,...,15.0,6.0,12,-6.0,0,SP -> SP,Early,2400.0,Light,Medium
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,2017-02-04,2017-03-01,2017-03-17,delivered,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.899994,18.139999,...,30.0,25.0,41,-16.0,0,PR -> SP,Early,42000.0,Heavy,Large

In [25]:
print(fact.columns)

Index(['order_id', 'customer_id', 'purchase_date', 'delivered_date',
       'estimated_date', 'order_status', 'product_id', 'seller_id', 'price',
       'freight_value', 'customer_city', 'customer_state', 'seller_city',
       'seller_state', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'delivery_days',
       'estimated_days', 'delay_days', 'delayed_flag', 'route_name',
       'delivery_status_bucket', 'volume_cm3', 'weight_bucket', 'size_bucket'],
      dtype='str')

In [26]:
print(fact.shape)

(113425, 27)

In [27]:
fact["route_type"] = fact.apply(
    lambda x: "Intra-State" if x["seller_state"] == x["customer_state"] else "Inter-State",
    axis=1
)

In [29]:
fact["route_type"].head(100)

0     Inter-State
1     Intra-State
2     Intra-State
3     Intra-State
4     Inter-State
         ...
95    Intra-State
96    Inter-State
97    Inter-State
98    Intra-State
99    Inter-State
Name: route_type, Length: 100, dtype: str

In [30]:
def delivery_speed(x):
    if pd.isna(x):
        return "Not Delivered"
    elif x <= 3:
        return "Fast"
    elif x <= 7:
        return "Standard"
    else:
        return "Slow"

fact["delivery_speed"] = fact["delivery_days"].apply(delivery_speed)

In [31]:
fact["delivery_speed"].head(10)

0    Standard
1        Slow
2        Slow
3    Standard
4        Slow
5    Standard
6        Slow
7    Standard
8        Slow
9        Fast
Name: delivery_speed, dtype: str

In [32]:
def freight_bucket(x):
    if pd.isna(x):
        return "Unknown"
    elif x <= 20:
        return "Low Cost"
    elif x <= 50:
        return "Medium Cost"
    else:
        return "High Cost"

fact["freight_bucket"] = fact["freight_value"].apply(freight_bucket)

In [33]:
fact["freight_bucket"].head(10)

0     Low Cost
1     Low Cost
2     Low Cost
3     Low Cost
4     Low Cost
5     Low Cost
6     Low Cost
7    High Cost
8     Low Cost
9     Low Cost
Name: freight_bucket, dtype: str

In [34]:
def order_value_bucket(x):
    if pd.isna(x):
        return "Unknown"
    elif x <= 50:
        return "Low Value"
    elif x <= 150:
        return "Medium Value"
    else:
        return "High Value"

fact["order_value_bucket"] = fact["price"].apply(order_value_bucket)

In [35]:
fact["order_value_bucket"].head(10)

0    Medium Value
1      High Value
2      High Value
3       Low Value
4      High Value
5       Low Value
6       Low Value
7      High Value
8    Medium Value
9    Medium Value
Name: order_value_bucket, dtype: str

In [36]:
fact["package_density"] = fact["product_weight_g"] / fact["volume_cm3"]

In [37]:
def density_bucket(x):
    if pd.isna(x):
        return "Unknown"
    elif x <= 0.05:
        return "Low Density"
    elif x <= 0.20:
        return "Medium Density"
    else:
        return "High Density"

fact["density_bucket"] = fact["package_density"].apply(density_bucket)

In [38]:
fact["density_bucket"].head(10)

0    Medium Density
1      High Density
2      High Density
3    Medium Density
4    Medium Density
5    Medium Density
6    Medium Density
7    Medium Density
8      High Density
9      High Density
Name: density_bucket, dtype: str

In [39]:
fact["delivery_risk_flag"] = fact.apply(
    lambda x: 1 if (x["delayed_flag"] == 1 and x["product_weight_g"] > 2000 and x["freight_value"] > 50) else 0,
    axis=1
)

In [40]:
fact["delivery_risk_flag"].head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: delivery_risk_flag, dtype: int64

In [41]:
fact["purchase_month"] = fact["purchase_date"].dt.month_name()
fact["purchase_year"] = fact["purchase_date"].dt.year
fact["purchase_quarter"] = "Q" + fact["purchase_date"].dt.quarter.astype(str)

In [42]:
fact.head()

,order_id,customer_id,purchase_date,delivered_date,estimated_date,order_status,product_id,seller_id,price,freight_value,...,route_type,delivery_speed,freight_bucket,order_value_bucket,package_density,density_bucket,delivery_risk_flag,purchase_month,purchase_year,purchase_quarter
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,2017-09-13,2017-09-20,2017-09-29,delivered,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.900002,13.290000,...,Inter-State,Standard,Low Cost,Medium Value,0.184240,Medium Density,0,September,2017,Q3
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,2017-04-26,2017-05-12,2017-05-15,delivered,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.899994,19.930000,...,Intra-State,Slow,Low Cost,High Value,0.500000,High Density,0,April,2017,Q2
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,2018-01-14,2018-01-22,2018-02-05,delivered,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.000000,17.870001,...,Intra-State,Slow,Low Cost,High Value,0.215441,High Density,0,January,2018,Q1
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,2018-08-08,2018-08-14,2018-08-20,delivered,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.990000,12.790000,...,Intra-State,Standard,Low Cost,Low Value,0.083333,Medium Density,0,August,2018,Q3
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,2017-02-04,2017-03-01,2017-03-17,delivered,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.899994,18.139999,...,Inter-State,Slow,Low Cost,High Value,0.089286,Medium Density,0,February,2017,Q1

In [43]:
print(fact.columns)

Index(['order_id', 'customer_id', 'purchase_date', 'delivered_date',
       'estimated_date', 'order_status', 'product_id', 'seller_id', 'price',
       'freight_value', 'customer_city', 'customer_state', 'seller_city',
       'seller_state', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'delivery_days',
       'estimated_days', 'delay_days', 'delayed_flag', 'route_name',
       'delivery_status_bucket', 'volume_cm3', 'weight_bucket', 'size_bucket',
       'route_type', 'delivery_speed', 'freight_bucket', 'order_value_bucket',
       'package_density', 'density_bucket', 'delivery_risk_flag',
       'purchase_month', 'purchase_year', 'purchase_quarter'],
      dtype='str')

In [44]:
fact.isnull().sum()

order_id                     0
customer_id                  0
purchase_date                0
delivered_date            3229
estimated_date               0
order_status                 0
product_id                 775
seller_id                  775
price                      775
freight_value              775
customer_city                0
customer_state               0
seller_city                775
seller_state               775
product_weight_g           793
product_length_cm          793
product_height_cm          793
product_width_cm           793
delivery_days             3229
estimated_days               0
delay_days                3229
delayed_flag                 0
route_name                 775
delivery_status_bucket       0
volume_cm3                 793
weight_bucket                0
size_bucket                  0
route_type                   0
delivery_speed               0
freight_bucket               0
order_value_bucket           0
package_density            793
density_bucket               0
delivery_risk_flag           0
purchase_month               0
purchase_year                0
purchase_quarter             0
dtype: int64

In [45]:
fact["purchase_month_num"] = fact["purchase_date"].dt.month

In [46]:
fact.to_csv("fact_delivery_enriched.csv", index=False)